### ISSUE TITLE
Segfault when issued "quit" during a search

### ISSUE THREAD

**Issue by AndyGrant** [jeffreyan11/uci-chess-engine#28] opened 2018-07-01 16:01 UTC
We are having an issue right know where on Linux machines cutechess does not kill every copy of your engine, only the 50% that are not searching when cutechess is closed down. 

It is possible that this is on my end, but since Ethereal works as expected here, I am looking into differences with Laser first. 

I'm not sure this is exactly the issue, but something I just noticed.

Happens under go depth, go infinite, and go wtime ...,

**Comment by jeffreyan11** [comment] 2018-07-01 18:22
You can send a "stop" before a "quit" to fix this. I will also fix it soon, I've just put it off because I haven't seen a GUI have problems with it yet.

**Comment by noobpwnftw** [comment] 2018-07-02 15:06
The hanging issue is not resolved by the recent commit.

**Comment by jeffreyan11** [comment] 2018-07-03 07:04
Hm, so the problem is not what I thought. It happens when cutechess cancels the match while a search is running? Does cutechess send stop before quit? Do you have logs?

**Comment by AndyGrant** [comment] 2018-07-04 04:38
So I ran a set with logging. No output from cutechess about stop/quit here. 

In this case I ran with concurrency=1, after the server tells cutechess to quit, half or all copies of master are left running. AND they are running at 100% CPU. 

Running your engine normally, so long as not searching, CPU usage is hardly enough to even make its way to the ``top`` view. This means after cutechess exits, you have a searching thread still running, despite the main input reader being dead.

I have done ``ps -T -p <pid>`` on the "dead" copies of Laser. I can clearly see only one thread running. When running your engine normally, sending ``go infinite``, I can then of course see the 2 threads using ``ps -T -p <pid>``

I'm not familiar with c++ threading, but you need to have your threads connected back to the main one in some way.

**Comment by AndyGrant** [comment] 2018-07-04 04:44
Assuming that cutechess is ACTUALLY sending a quit command to Laser (and not reporting it), all you might need to do is ensure that the search thread is joined before termination.

**Comment by AndyGrant** [comment] 2018-07-04 04:47
See https://stackoverflow.com/questions/3756882/detached-vs-joinable-posix-threads and https://stackoverflow.com/questions/25655706/how-to-terminate-or-stop-a-detached-thread-in-c

**Comment by AndyGrant** [comment] 2018-08-01 17:28
Have you looked any further into this? I tried a few things which in some cases suggested progress, other cases nothing.

**Comment by laldon** [comment] 2018-08-11 13:25
*bump* @jeffreyan11 @AndyGrant

**Closed as completed** 2018-08-11 14:33 UTC
