### ISSUE TITLE
Laser for android

### ISSUE THREAD

**Issue by Alexei1981** [jeffreyan11/uci-chess-engine#7] opened 2018-01-11 14:02 UTC
I have a question: I'm porting the engines to android and they all work fine, but with the laser engine problem. It's easy to compile, but when playing for example black, on the 3rd payday for blacks and for whites constantly makes wrong moves and loses (For example 1.e2 -e4 ​​e7-e5 2.kg1-f3 2 ... here Laser does wrong move and loses). Here are examples:

[Event "Chess for Android Tournament"]
[Date "2018.01.11"]
[Round "2"]
[White "Laser 1.6 beta"]
[Black "Chiron 4"]
[Result "0-1"]
[TimeControl "60+1"]
[PlyCount "2"]
[Device "ZTE BLADE A210"]

1. d4 {[11/18]25/d7d5 2.469} 1... d5 {[14/24]-39/c2c4 4.117} 2. --
{[%playeraction resign]} 0-1

[Event "Chess for Android Tournament"]
[Date "2018.01.11"]
[Round "1"]
[White "Chiron 4"]
[Black "Laser 1.6 beta"]
[Result "1-0"]
[TimeControl "60+1"]
[PlyCount "3"]
[Device "ZTE BLADE A210"]

1. e4 {[16/31]32/d7d5 13.683} 1... c5 {[11/22]-24/g1f3 2.445} 2. Nf3
{[14/27]46/b8c6 2.318} 2... -- {[%playeraction resign]} 1-0

**Comment by Alexei1981** [comment] 2018-01-11 14:08
As far as I understand, the problem is in the "position" command. Can I fix this? For example, make this command like stockfish (it works fine, like the other engines). I would like to see a strong Laser engine on the android (I was tortured by chess fans). Thank you.

**Comment by Alexei1981** [comment] 2018-01-13 18:32
I solved this problem by making such a change to the file uci.cpp:

if (input.find("moves") != string::npos) {
        string moveList = input.substr(input.find("moves") + 6);
        std::vector<string> moveVector = split(moveList, ' ');
        
        std::istringstream is(moveList);
		std::string moveStr;
		
		while(is >> moveStr){

        //for (unsigned i = 0; i < moveVector.size(); i++) {
            // moveStr contains the move in long algebraic notation
            //string moveStr = moveVector.at(i);
            bool reversible;
            Move m = stringToMove(moveStr, board, reversible);

**Comment by jeffreyan11** [comment] 2018-01-15 08:45
Thanks for the report! I have made some bugfix commits, hopefully the problem is fixed now.

**Closed as completed by jeffreyan11** 2018-01-15 08:45 UTC

**Comment by Alexei1981** [comment] 2018-01-15 10:26
Yes, now it's working fine.
Thanks.
